version: '3'
services:
    database: 
        image: mongo
        container_name: "mongodb-container"
        volumes:
         - ./api/mongo-volume:/data/db
        ports:
         - 27017:27017
    api:
        build: api/.
        container_name: spring_docker
        environment:
         - MONGODB_STATUS_HOST=database
        ports:
         - 8080:8080
        depends_on:
         - database
